apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  selector:
    matchLabels:
      app: result
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: iamnilanjan3/result:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     app: result   
